export const DEFAULT_INDICATORS = [
  {
    id: "roads",
    rank: 1,
    name: "Major road closures",
    category: "Tier 1",
    weight: 10,
    icon: "Route",
    watch: "National routes, logistics corridors, weather closures, blockades, and event restrictions.",
    why: "Mobility usually degrades before most people recognise that the operating environment changed.",
    sourceIds: ["google-news-rss", "sanews", "sanral-reference"],
  },
  {
    id: "fuel",
    rank: 2,
    name: "Fuel availability",
    category: "Tier 1",
    weight: 10,
    icon: "Fuel",
    watch: "Supply reassurance, levy shocks, imports, refinery maintenance, queue behaviour, and rationing language.",
    why: "Fuel controls transport, generators, delivery chains, and how much optional movement a household can still buy.",
    sourceIds: ["google-news-rss", "gov-fuel"],
  },
  {
    id: "political-triggers",
    rank: 3,
    name: "Political trigger dates",
    category: "Tier 1",
    weight: 10,
    icon: "Siren",
    watch: "Court rulings, arrests, parliamentary flashpoints, and sudden executive announcements.",
    why: "Political shocks can move crowds and narratives much faster than slow-burn social stress.",
    sourceIds: ["google-news-rss", "parliament-press"],
  },
  {
    id: "mobilization",
    rank: 4,
    name: "Coordinated protest calls",
    category: "Tier 1",
    weight: 9,
    icon: "Users",
    watch: "Taxi strikes, shutdown calls, anti-immigration marches, unions, and organised local campaigns.",
    why: "Structured mobilisation creates far more disruption than scattered anger.",
    sourceIds: ["google-news-rss", "saps-newsroom"],
  },
  {
    id: "police-capacity",
    rank: 5,
    name: "Police capacity and overstretch",
    category: "Tier 1",
    weight: 9,
    icon: "Shield",
    watch: "Official operation updates, parliamentary concern, delayed response language, and visible multi-point pressure.",
    why: "If response capacity thins out, opportunistic crime expands into the gap very quickly.",
    sourceIds: ["google-news-rss", "saps-newsroom", "parliament-press"],
  },
  {
    id: "local-protests",
    rank: 6,
    name: "Local protest activity",
    category: "Tier 2",
    weight: 8,
    icon: "Activity",
    watch: "Town-level road blocks, municipal anger, burning tyres, service-delivery action, and commuter disruption.",
    why: "Local disruptions are often what directly changes a family movement decision.",
    sourceIds: ["google-news-rss", "parliament-press"],
  },
  {
    id: "food-pharmacy",
    rank: 7,
    name: "Food and pharmacy availability",
    category: "Tier 2",
    weight: 8,
    icon: "Home",
    watch: "Shortages, panic buying, pharmacy stock concerns, and sharp supply-chain stress.",
    why: "Retail fragility is household pressure, not abstract macro commentary.",
    sourceIds: ["google-news-rss", "pmbejd-data"],
  },
  {
    id: "firearms",
    rank: 8,
    name: "Weapon thefts and firearm seizures",
    category: "Tier 3",
    weight: 7,
    icon: "AlertTriangle",
    watch: "Rifles, ammunition seizures, stolen police weapons, and organised cache discoveries.",
    why: "Escalation risk rises when violent capability shows up alongside social or political friction.",
    sourceIds: ["google-news-rss", "saps-newsroom"],
  },
  {
    id: "misinfo",
    rank: 9,
    name: "Viral misinformation spikes",
    category: "Tier 4",
    weight: 6,
    icon: "Radio",
    watch: "Fake video warnings, recycled clips, WhatsApp panic chains, and false closure claims.",
    why: "Fear travels faster than verification, which is irritating but operationally relevant.",
    sourceIds: ["google-news-rss", "gov-cabinet"],
  },
  {
    id: "family-readiness",
    rank: 10,
    name: "Family readiness score",
    category: "Personal",
    weight: 10,
    icon: "CheckCircle2",
    watch: "Water, food, fuel, cash, medicine, documents, routes, comms, and fallback plans.",
    why: "Preparedness is still the one variable you fully control.",
    sourceIds: [],
  },
];
