export const DEFAULT_INDICATORS = [
  {
    id: "roads",
    rank: 1,
    name: "Major road closures",
    category: "Tier 1",
    weight: 10,
    score: 0,
    icon: "Route",
    watch: "N1, N2, N3, N12, major interchanges, logistics corridors.",
    why: "Mobility disappears before most people realize risk has changed.",
  },
  {
    id: "fuel",
    rank: 2,
    name: "Fuel availability",
    category: "Tier 1",
    weight: 10,
    score: 0,
    icon: "Fuel",
    watch: "Queues, closures, rationing, tanker disruptions, station cash-only behavior.",
    why: "Fuel controls mobility, generators, logistics, and security response.",
  },
  {
    id: "political-triggers",
    rank: 3,
    name: "Political trigger dates",
    category: "Tier 1",
    weight: 10,
    score: 0,
    icon: "Siren",
    watch: "Impeachment votes, court rulings, sentencing, arrests, appeal decisions.",
    why: "Legal or political shocks can rapidly mobilize crowds and narratives.",
  },
  {
    id: "mobilization",
    rank: 4,
    name: "Coordinated protest calls",
    category: "Tier 1",
    weight: 9,
    score: 0,
    icon: "Users",
    watch: "National shutdowns, EFF calls, taxi strikes, union escalation, campus unrest.",
    why: "Organized unrest is more dangerous than scattered anger.",
  },
  {
    id: "police-capacity",
    rank: 5,
    name: "Police capacity / overstretch",
    category: "Tier 1",
    weight: 9,
    score: 0,
    icon: "Shield",
    watch: "Delayed responses, SAPS stations attacked, POP redeployment, visible withdrawal.",
    why: "If police containment fails, opportunistic crime rises fast.",
  },
  {
    id: "local-protests",
    rank: 6,
    name: "Local protest activity",
    category: "Tier 2",
    weight: 8,
    score: 0,
    icon: "Activity",
    watch: "Nearby marches, burning tyres, service-delivery protests, road blockages.",
    why: "Local events affect immediate family movement decisions.",
  },
  {
    id: "food-pharmacy",
    rank: 7,
    name: "Food / pharmacy availability",
    category: "Tier 2",
    weight: 8,
    score: 0,
    icon: "Home",
    watch: "Closures, panic buying, empty shelves, medicine shortages, distribution issues.",
    why: "Retail failure is a practical household pressure signal.",
  },
  {
    id: "firearms",
    rank: 8,
    name: "Weapon thefts / firearm seizures",
    category: "Tier 3",
    weight: 7,
    score: 0,
    icon: "AlertTriangle",
    watch: "SAPS/SANDF thefts, automatic rifles, ammunition seizures, repeated patterns.",
    why: "Violence capacity matters more when paired with political or social triggers.",
  },
  {
    id: "misinfo",
    rank: 9,
    name: "Viral misinformation spikes",
    category: "Tier 4",
    weight: 6,
    score: 0,
    icon: "Radio",
    watch: "Old riot clips, fake locations, WhatsApp voice notes, racial panic claims.",
    why: "Fear can move people faster than facts. Tedious, but true.",
  },
  {
    id: "family-readiness",
    rank: 10,
    name: "Family readiness score",
    category: "Personal",
    weight: 10,
    score: 0,
    icon: "CheckCircle2",
    watch: "Water, food, fuel, cash, medicine, documents, routes, comms, fallback plan.",
    why: "Preparedness turns bad information into better decisions.",
  },
];
